#pragma once

#define AS_GROUP_SIZE 1
#define MAX_MSGROUPS_PER_ASGROUP 512
#define MAX_TRIANGLES_PER_GROUP 85
#define MAX_LINES_PER_GROUP 128
#define NUM_INSTANCES 50

#define NUM_DIR_LIGHTS 1
#define NUM_POINT_LIGHTS 2

#define NUM_LIGHTS (NUM_DIR_LIGHTS + NUM_POINT_LIGHTS)
